### ISSUE TITLE
Upload a file it seems to change encoding

### ISSUE THREAD

**Issue by wsmelton** [tylerl0706/azure-cloud-shell-app#2]
Downloaded a PS file and encoding is UTF-8, but seems it is adding characters for some reason:

![image](https://user-images.githubusercontent.com/11204251/38341604-05d2079c-383f-11e8-9532-b91a411ec63a.png)

As viewed from VS Code on the same file:
![image](https://user-images.githubusercontent.com/11204251/38341633-2abac6b6-383f-11e8-9419-b7b97fe938c3.png)

**Comment by TylerLeonhardt** [comment]
Thanks for this! 

How does this look in shell.azure.com?

**Comment by wsmelton** [comment]
Ok, so this is not related to your app...I get the same result uploading the file via the Portal.

**Comment by wsmelton** [comment]
I ended up having to just rewrite that line and those special characters stopped showing up.

**Comment by TylerLeonhardt** [comment]
Glad you figured it out!
